apiVersion: apps/v1
kind: Deployment
metadata:
  name: courses-service
  labels:
    app: courses
spec:
  replicas: 3
  selector:
    matchLabels:
      app: courses
  template:
    metadata:
      labels:
        app: courses
    spec:
      containers:
      - name: courses-service
        image: your-docker-repo/courses-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb://mongo:27017/courses
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://config-server:8888
---
apiVersion: v1
kind: Service
metadata:
  name: courses-service
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: courses