apiVersion: apps/v1
kind: Deployment
metadata:
  name: courses-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: courses-service
  template:
    metadata:
      labels:
        app: courses-service
    spec:
      containers:
        - name: courses-service
          image: mbardus/courses-service:latest
          ports:
            - containerPort: 8080