name: Courses CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker image
        run: |
          docker build -t courses-service .

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag courses-service your-docker-repo/courses-service:latest
          docker push your-docker-repo/courses-service:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ../k8s/courses-deployment.yaml