name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Add execute permission to ng
        run: chmod +x ./node_modules/.bin/ng
        working-directory: frontend

      - name: Build the application
        run: npm run build --prod
        working-directory: frontend
